-- Battle Spirits Eternal Simulator v4.2.0
-- Dual economy + collection foundation.
-- Spirit Coins: Store currency.
-- Craft Coins: crafting-only currency.

begin;

create table if not exists public.bs_player_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  spirit_coins bigint not null default 0 check (spirit_coins >= 0),
  craft_coins bigint not null default 0 check (craft_coins >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.bs_player_cards (
  user_id uuid not null references auth.users(id) on delete cascade,
  card_id text not null,
  quantity integer not null default 0 check (quantity >= 0),
  acquired_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, card_id)
);

create table if not exists public.bs_economy_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  currency text not null check (currency in ('spirit','craft')),
  amount bigint not null,
  reason text not null,
  source_uid text,
  created_at timestamptz not null default now()
);

create unique index if not exists bs_economy_ledger_source_unique
  on public.bs_economy_ledger(user_id, currency, source_uid)
  where source_uid is not null;

create index if not exists bs_player_cards_user_idx on public.bs_player_cards(user_id);
create index if not exists bs_economy_ledger_user_created_idx on public.bs_economy_ledger(user_id, created_at desc);

alter table public.bs_player_wallets enable row level security;
alter table public.bs_player_cards enable row level security;
alter table public.bs_economy_ledger enable row level security;

drop policy if exists "Players can read own wallet" on public.bs_player_wallets;
create policy "Players can read own wallet"
  on public.bs_player_wallets for select
  using (auth.uid() = user_id);

drop policy if exists "Players can read own collection" on public.bs_player_cards;
create policy "Players can read own collection"
  on public.bs_player_cards for select
  using (auth.uid() = user_id);

drop policy if exists "Players can read own economy ledger" on public.bs_economy_ledger;
create policy "Players can read own economy ledger"
  on public.bs_economy_ledger for select
  using (auth.uid() = user_id);

-- No INSERT/UPDATE/DELETE policies are intentionally exposed to the client.
-- Future match rewards, purchases, crafting and trading must mutate balances
-- through trusted server-side code so a player cannot mint currency/cards.

create or replace function public.bs_create_economy_account()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.bs_player_wallets(user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists bs_auth_create_economy_account on auth.users;
create trigger bs_auth_create_economy_account
after insert on auth.users
for each row execute function public.bs_create_economy_account();

insert into public.bs_player_wallets(user_id)
select id from auth.users
on conflict (user_id) do nothing;

create or replace function public.bs_ensure_economy_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return;
  end if;
  insert into public.bs_player_wallets(user_id)
  values (auth.uid())
  on conflict (user_id) do nothing;
end;
$$;

revoke all on function public.bs_ensure_economy_account() from public;
grant execute on function public.bs_ensure_economy_account() to authenticated;

grant select on public.bs_player_wallets to authenticated;
grant select on public.bs_player_cards to authenticated;
grant select on public.bs_economy_ledger to authenticated;

commit;
