-- Battle Spirits Eternal Simulator v4.3.0
-- Crafting + restricted economy/gameplay administration.
-- This migration never exposes auth.users credentials, passwords or tokens.

begin;

alter table if exists public.bs_player_progress
  add column if not exists account_status text not null default 'active'
  check (account_status in ('active','restricted','suspended'));

create table if not exists public.bs_admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin','owner')),
  created_at timestamptz not null default now()
);

create table if not exists public.bs_admin_economy_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  target_user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  currency text,
  amount bigint,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.bs_admin_users enable row level security;
alter table public.bs_admin_economy_log enable row level security;

revoke all on public.bs_admin_users from anon, authenticated;
revoke all on public.bs_admin_economy_log from anon, authenticated;

create or replace function public.bs_admin_has_access()
returns boolean
language sql
security definer
set search_path = public
as $$
  select auth.uid() is not null
    and exists(select 1 from public.bs_admin_users where user_id = auth.uid());
$$;

create or replace function public.bs_admin_list_players(p_query text default '')
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_query text := lower(trim(coalesce(p_query,'')));
begin
  if not public.bs_admin_has_access() then
    raise exception 'ADMIN_REQUIRED';
  end if;

  return coalesce((
    select jsonb_agg(
      jsonb_build_object(
        'user_id', p.id,
        'username', p.username,
        'display_name', p.display_name,
        'spirit_coins', coalesce(w.spirit_coins,0),
        'craft_coins', coalesce(w.craft_coins,0),
        'account_status', coalesce(g.account_status,'active')
      )
      order by lower(coalesce(p.display_name,p.username))
    )
    from public.bs_profiles p
    left join public.bs_player_wallets w on w.user_id = p.id
    left join public.bs_player_progress g on g.user_id = p.id
    where v_query = ''
       or lower(coalesce(p.display_name,'')) like '%'||v_query||'%'
       or lower(coalesce(p.username,'')) like '%'||v_query||'%'
  ), '[]'::jsonb);
end;
$$;

create or replace function public.bs_admin_adjust_currency(
  p_target_user uuid,
  p_currency text,
  p_amount bigint,
  p_reason text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_wallet public.bs_player_wallets%rowtype;
  v_currency text := lower(trim(coalesce(p_currency,'')));
begin
  if not public.bs_admin_has_access() then
    raise exception 'ADMIN_REQUIRED';
  end if;
  if p_target_user is null then raise exception 'TARGET_REQUIRED'; end if;
  if v_currency not in ('spirit','craft') then raise exception 'INVALID_CURRENCY'; end if;
  if p_amount = 0 then raise exception 'AMOUNT_REQUIRED'; end if;

  insert into public.bs_player_wallets(user_id) values(p_target_user)
  on conflict(user_id) do nothing;

  if v_currency = 'spirit' then
    update public.bs_player_wallets
      set spirit_coins = greatest(0, spirit_coins + p_amount), updated_at = now()
      where user_id = p_target_user
      returning * into v_wallet;
  else
    update public.bs_player_wallets
      set craft_coins = greatest(0, craft_coins + p_amount), updated_at = now()
      where user_id = p_target_user
      returning * into v_wallet;
  end if;

  insert into public.bs_admin_economy_log(admin_user_id,target_user_id,action,currency,amount,reason)
  values(auth.uid(),p_target_user,'currency_adjustment',v_currency,p_amount,left(coalesce(p_reason,''),240));

  return jsonb_build_object(
    'userId', p_target_user,
    'spiritCoins', v_wallet.spirit_coins,
    'craftCoins', v_wallet.craft_coins
  );
end;
$$;

create or replace function public.bs_admin_set_player_status(
  p_target_user uuid,
  p_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_status text := lower(trim(coalesce(p_status,'')));
begin
  if not public.bs_admin_has_access() then
    raise exception 'ADMIN_REQUIRED';
  end if;
  if v_status not in ('active','restricted','suspended') then
    raise exception 'INVALID_STATUS';
  end if;

  insert into public.bs_player_progress(user_id,account_status)
  values(p_target_user,v_status)
  on conflict(user_id) do update set account_status = excluded.account_status, updated_at = now();

  insert into public.bs_admin_economy_log(admin_user_id,target_user_id,action,reason)
  values(auth.uid(),p_target_user,'status_change',v_status);

  return jsonb_build_object('userId',p_target_user,'status',v_status);
end;
$$;

create or replace function public.bs_craft_card(
  p_card_id text,
  p_rarity text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_owned integer := 0;
  v_rarity text := upper(trim(coalesce(p_rarity,'C')));
  v_base integer;
  v_cost integer;
  v_craft bigint;
  v_status text;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if coalesce(trim(p_card_id),'') = '' then raise exception 'CARD_REQUIRED'; end if;

  insert into public.bs_player_wallets(user_id) values(v_user) on conflict(user_id) do nothing;
  insert into public.bs_player_progress(user_id) values(v_user) on conflict(user_id) do nothing;

  select account_status into v_status from public.bs_player_progress where user_id=v_user;
  if coalesce(v_status,'active') = 'suspended' then raise exception 'ACCOUNT_SUSPENDED'; end if;

  select quantity into v_owned
  from public.bs_player_cards
  where user_id=v_user and card_id=p_card_id
  for update;
  v_owned := coalesce(v_owned,0);
  if v_owned >= 6 then raise exception 'MAX_OWNED_COPIES'; end if;

  v_base := case v_rarity
    when 'C' then 40 when 'U' then 80 when 'R' then 160 when 'M' then 320
    when 'X' then 640 when 'XX' then 960 when 'CP' then 400
    when 'CX' then 800 when 'TX' then 800 when 'PX' then 960
    else 40 end;
  v_cost := case when v_owned > 0 then greatest(1,round(v_base * 0.75)) else v_base end;

  select craft_coins into v_craft from public.bs_player_wallets where user_id=v_user for update;
  if coalesce(v_craft,0) < v_cost then raise exception 'INSUFFICIENT_CRAFT_COINS'; end if;

  update public.bs_player_wallets
    set craft_coins=craft_coins-v_cost, updated_at=now()
    where user_id=v_user;

  insert into public.bs_player_cards(user_id,card_id,quantity,updated_at)
  values(v_user,p_card_id,1,now())
  on conflict(user_id,card_id) do update
    set quantity=least(6,bs_player_cards.quantity+1), updated_at=now();

  return jsonb_build_object(
    'cardId',p_card_id,
    'before',v_owned,
    'after',v_owned+1,
    'cost',v_cost,
    'discounted',v_owned>0
  );
end;
$$;

grant execute on function public.bs_admin_has_access() to authenticated;
grant execute on function public.bs_admin_list_players(text) to authenticated;
grant execute on function public.bs_admin_adjust_currency(uuid,text,bigint,text) to authenticated;
grant execute on function public.bs_admin_set_player_status(uuid,text) to authenticated;
grant execute on function public.bs_craft_card(text,text) to authenticated;

commit;

-- OWNER SETUP (run once in Supabase SQL editor after replacing the UUID):
-- insert into public.bs_admin_users(user_id, role)
-- values ('YOUR_AUTH_USER_UUID'::uuid, 'owner')
-- on conflict (user_id) do update set role='owner';
