-- Battle Spirits Eternal Simulator v3.6.0
-- SOCIAL HUB / PLAYER IDENTITY
-- Migration idempotente para perfis, privacidade, amizade, chat e notificações.
-- Execute uma vez no SQL Editor do mesmo projeto Supabase já usado pelo simulador.

begin;

-- Base mínima para que a migração também funcione em um projeto Supabase novo.
create table if not exists public.bs_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 24),
  display_name text not null default 'Jogador',
  bio text not null default '',
  avatar text,
  banner text,
  updated_at timestamptz not null default now()
);

create table if not exists public.bs_friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.bs_profiles(id) on delete cascade,
  addressee_id uuid not null references public.bs_profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(),
  unique(requester_id, addressee_id),
  check (requester_id <> addressee_id)
);

create table if not exists public.bs_direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.bs_profiles(id) on delete cascade,
  recipient_id uuid not null references public.bs_profiles(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.bs_player_decks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  decks jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.bs_profiles enable row level security;
alter table public.bs_friendships enable row level security;
alter table public.bs_direct_messages enable row level security;
alter table public.bs_player_decks enable row level security;

alter table public.bs_profiles
  add column if not exists profile_visibility text not null default 'public',
  add column if not exists friend_request_policy text not null default 'everyone',
  add column if not exists message_policy text not null default 'friends',
  add column if not exists discoverable boolean not null default true,
  add column if not exists show_online_status boolean not null default true,
  add column if not exists show_stats boolean not null default true,
  add column if not exists show_decks boolean not null default true,
  add column if not exists show_mastery boolean not null default true,
  add column if not exists presence_status text not null default 'offline',
  add column if not exists last_seen_at timestamptz;

-- Checks são recriados de forma segura para bancos que já possuem a tabela.
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'bs_profiles_visibility_check') then
    alter table public.bs_profiles add constraint bs_profiles_visibility_check
      check (profile_visibility in ('public','friends','private'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bs_profiles_friend_policy_check') then
    alter table public.bs_profiles add constraint bs_profiles_friend_policy_check
      check (friend_request_policy in ('everyone','mutuals','nobody'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bs_profiles_message_policy_check') then
    alter table public.bs_profiles add constraint bs_profiles_message_policy_check
      check (message_policy in ('friends','everyone','nobody'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bs_profiles_presence_check') then
    alter table public.bs_profiles add constraint bs_profiles_presence_check
      check (presence_status in ('online','away','busy','offline','invisible'));
  end if;
end $$;

alter table public.bs_friendships
  alter column status set default 'pending';

alter table public.bs_friendships
  add column if not exists updated_at timestamptz not null default now();

alter table public.bs_direct_messages
  add column if not exists read_at timestamptz,
  add column if not exists edited_at timestamptz;

create table if not exists public.bs_player_blocks (
  blocker_id uuid not null references public.bs_profiles(id) on delete cascade,
  blocked_id uuid not null references public.bs_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

create table if not exists public.bs_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.bs_profiles(id) on delete cascade,
  type text not null check (type in ('friend_request','friend_accepted','message','system')),
  actor_id uuid references public.bs_profiles(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists bs_friendships_requester_idx on public.bs_friendships(requester_id, status);
create index if not exists bs_friendships_addressee_idx on public.bs_friendships(addressee_id, status);
create index if not exists bs_messages_pair_idx on public.bs_direct_messages(sender_id, recipient_id, created_at desc);
create index if not exists bs_messages_unread_idx on public.bs_direct_messages(recipient_id, read_at, created_at desc);
create index if not exists bs_notifications_user_idx on public.bs_notifications(user_id, read_at, created_at desc);
create index if not exists bs_profiles_username_lower_idx on public.bs_profiles(lower(username));

alter table public.bs_player_blocks enable row level security;
alter table public.bs_notifications enable row level security;

create or replace function public.bs_are_friends(a uuid, b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.bs_friendships f
    where f.status = 'accepted'
      and ((f.requester_id = a and f.addressee_id = b)
        or (f.requester_id = b and f.addressee_id = a))
  );
$$;

create or replace function public.bs_is_blocked(a uuid, b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.bs_player_blocks x
    where (x.blocker_id = a and x.blocked_id = b)
       or (x.blocker_id = b and x.blocked_id = a)
  );
$$;

create or replace function public.bs_has_mutual_friend(a uuid, b uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  with friends_a as (
    select case when requester_id = a then addressee_id else requester_id end as friend_id
    from public.bs_friendships
    where status = 'accepted' and (requester_id = a or addressee_id = a)
  ), friends_b as (
    select case when requester_id = b then addressee_id else requester_id end as friend_id
    from public.bs_friendships
    where status = 'accepted' and (requester_id = b or addressee_id = b)
  )
  select exists (select 1 from friends_a join friends_b using(friend_id));
$$;

create or replace function public.bs_can_message(sender uuid, recipient uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    sender = recipient
    or (
      not public.bs_is_blocked(sender, recipient)
      and exists (
        select 1 from public.bs_profiles p
        where p.id = recipient
          and (
            p.message_policy = 'everyone'
            or (p.message_policy = 'friends' and public.bs_are_friends(sender, recipient))
          )
      )
    );
$$;

-- Perfis: dono vê tudo; demais só recebem a linha quando a visibilidade permitir.
drop policy if exists "profiles readable" on public.bs_profiles;
drop policy if exists "profiles visible by privacy" on public.bs_profiles;
create policy "profiles visible by privacy"
on public.bs_profiles for select to authenticated
using (
  auth.uid() = id
  or profile_visibility = 'public'
  or (profile_visibility = 'friends' and public.bs_are_friends(auth.uid(), id))
);

drop policy if exists "profile owner write" on public.bs_profiles;
create policy "profile owner write" on public.bs_profiles for all to authenticated
using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "friendships visible to participants" on public.bs_friendships;
create policy "friendships visible to participants" on public.bs_friendships for select to authenticated
using (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "messages participants read" on public.bs_direct_messages;
create policy "messages participants read" on public.bs_direct_messages for select to authenticated
using (auth.uid() = sender_id or auth.uid() = recipient_id);

drop policy if exists "decks owner" on public.bs_player_decks;
create policy "decks owner" on public.bs_player_decks for all to authenticated
using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Amizades: o cliente só pode criar pedidos pendentes. Aceitar/recusar/remover
-- passa pelas RPCs security-definer abaixo, evitando auto-aceite pelo requester.
drop policy if exists "friendship create self" on public.bs_friendships;
create policy "friendship create pending self" on public.bs_friendships for insert to authenticated
with check (auth.uid() = requester_id and status = 'pending');
drop policy if exists "friendship participant update" on public.bs_friendships;

-- Bloqueios são privados ao dono.
drop policy if exists "blocks owner select" on public.bs_player_blocks;
create policy "blocks owner select" on public.bs_player_blocks for select to authenticated
using (auth.uid() = blocker_id);
drop policy if exists "blocks owner insert" on public.bs_player_blocks;
create policy "blocks owner insert" on public.bs_player_blocks for insert to authenticated
with check (auth.uid() = blocker_id);
drop policy if exists "blocks owner delete" on public.bs_player_blocks;
create policy "blocks owner delete" on public.bs_player_blocks for delete to authenticated
using (auth.uid() = blocker_id);

-- Notificações são somente do destinatário.
drop policy if exists "notifications owner select" on public.bs_notifications;
create policy "notifications owner select" on public.bs_notifications for select to authenticated
using (auth.uid() = user_id);
drop policy if exists "notifications owner update" on public.bs_notifications;
drop policy if exists "notifications owner delete" on public.bs_notifications;
create policy "notifications owner delete" on public.bs_notifications for delete to authenticated
using (auth.uid() = user_id);

-- Mensagens: leitura só dos participantes e envio respeitando privacidade/bloqueios.
drop policy if exists "messages sender insert" on public.bs_direct_messages;
create policy "messages sender insert" on public.bs_direct_messages for insert to authenticated
with check (auth.uid() = sender_id and public.bs_can_message(sender_id, recipient_id));
drop policy if exists "messages recipient update read" on public.bs_direct_messages;

-- Busca segura: perfis privados continuam localizáveis apenas com identidade mínima
-- quando o jogador permite discoverability. Bio/banner não são expostos aqui.
create or replace function public.bs_search_profiles(search_text text)
returns table(
  id uuid,
  username text,
  display_name text,
  avatar text,
  profile_visibility text,
  relation_status text
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.username,
    p.display_name,
    case
      when p.profile_visibility = 'private' and not public.bs_are_friends(auth.uid(), p.id) then null
      else p.avatar
    end as avatar,
    p.profile_visibility,
    coalesce((
      select f.status from public.bs_friendships f
      where (f.requester_id = auth.uid() and f.addressee_id = p.id)
         or (f.requester_id = p.id and f.addressee_id = auth.uid())
      order by f.updated_at desc nulls last, f.created_at desc
      limit 1
    ), 'none') as relation_status
  from public.bs_profiles p
  where p.id <> auth.uid()
    and p.discoverable = true
    and not public.bs_is_blocked(auth.uid(), p.id)
    and (
      p.username ilike '%' || trim(search_text) || '%'
      or p.display_name ilike '%' || trim(search_text) || '%'
    )
  order by p.display_name asc
  limit 20;
$$;

create or replace function public.bs_get_social_profile(target_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  p public.bs_profiles%rowtype;
  can_view boolean;
  is_friend boolean;
begin
  select * into p from public.bs_profiles where id = target_id;
  if not found or public.bs_is_blocked(auth.uid(), target_id) then return null; end if;

  is_friend := public.bs_are_friends(auth.uid(), target_id);
  can_view := auth.uid() = target_id or p.profile_visibility = 'public' or (p.profile_visibility = 'friends' and is_friend);

  return jsonb_build_object(
    'id', p.id,
    'username', p.username,
    'display_name', p.display_name,
    'avatar', case when can_view then p.avatar else null end,
    'banner', case when can_view then p.banner else null end,
    'bio', case when can_view then p.bio else '' end,
    'profile_visibility', p.profile_visibility,
    'is_friend', is_friend,
    'can_message', public.bs_can_message(auth.uid(), target_id),
    'can_view', can_view,
    'show_online_status', case when can_view then p.show_online_status else false end,
    'presence_status', case when can_view and p.show_online_status then p.presence_status else 'hidden' end,
    'last_seen_at', case when can_view and p.show_online_status then p.last_seen_at else null end,
    'show_stats', can_view and p.show_stats,
    'show_decks', can_view and p.show_decks,
    'show_mastery', can_view and p.show_mastery
  );
end;
$$;

create or replace function public.bs_send_friend_request(target_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  policy_value text;
  existing_id bigint;
  reverse_pending bigint;
begin
  if auth.uid() is null then return jsonb_build_object('ok', false, 'error', 'AUTH_REQUIRED'); end if;
  if target_id = auth.uid() then return jsonb_build_object('ok', false, 'error', 'SELF_REQUEST'); end if;
  if public.bs_is_blocked(auth.uid(), target_id) then return jsonb_build_object('ok', false, 'error', 'BLOCKED'); end if;

  select friend_request_policy into policy_value from public.bs_profiles where id = target_id;
  if policy_value is null then return jsonb_build_object('ok', false, 'error', 'PROFILE_NOT_FOUND'); end if;
  if policy_value = 'nobody' then return jsonb_build_object('ok', false, 'error', 'REQUESTS_DISABLED'); end if;
  if policy_value = 'mutuals' and not public.bs_has_mutual_friend(auth.uid(), target_id) then
    return jsonb_build_object('ok', false, 'error', 'MUTUALS_ONLY');
  end if;

  if public.bs_are_friends(auth.uid(), target_id) then
    return jsonb_build_object('ok', true, 'status', 'accepted');
  end if;

  select id into reverse_pending from public.bs_friendships
  where requester_id = target_id and addressee_id = auth.uid() and status = 'pending'
  limit 1;
  if reverse_pending is not null then
    update public.bs_friendships set status='accepted', updated_at=now() where id=reverse_pending;
    return jsonb_build_object('ok', true, 'status', 'accepted');
  end if;

  select id into existing_id from public.bs_friendships
  where requester_id = auth.uid() and addressee_id = target_id
  limit 1;

  if existing_id is null then
    insert into public.bs_friendships(requester_id, addressee_id, status)
    values(auth.uid(), target_id, 'pending');
  else
    update public.bs_friendships set status='pending', updated_at=now() where id=existing_id;
  end if;

  return jsonb_build_object('ok', true, 'status', 'pending');
end;
$$;

create or replace function public.bs_respond_friend_request(request_id bigint, response text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  row_data public.bs_friendships%rowtype;
begin
  select * into row_data from public.bs_friendships where id = request_id and status = 'pending';
  if not found or row_data.addressee_id <> auth.uid() then
    return jsonb_build_object('ok', false, 'error', 'REQUEST_NOT_FOUND');
  end if;

  if response = 'accept' then
    update public.bs_friendships set status='accepted', updated_at=now() where id=request_id;
    return jsonb_build_object('ok', true, 'status', 'accepted');
  elsif response = 'decline' then
    delete from public.bs_friendships where id=request_id;
    return jsonb_build_object('ok', true, 'status', 'declined');
  end if;

  return jsonb_build_object('ok', false, 'error', 'INVALID_RESPONSE');
end;
$$;

create or replace function public.bs_remove_friend(target_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  delete from public.bs_friendships
  where status = 'accepted'
    and ((requester_id = auth.uid() and addressee_id = target_id)
      or (requester_id = target_id and addressee_id = auth.uid()));
  select true;
$$;

create or replace function public.bs_block_user(target_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if target_id = auth.uid() then return false; end if;
  insert into public.bs_player_blocks(blocker_id, blocked_id)
  values(auth.uid(), target_id)
  on conflict do nothing;
  delete from public.bs_friendships
  where (requester_id = auth.uid() and addressee_id = target_id)
     or (requester_id = target_id and addressee_id = auth.uid());
  return true;
end;
$$;

create or replace function public.bs_unblock_user(target_id uuid)
returns boolean
language sql
security definer
set search_path = public
as $$
  delete from public.bs_player_blocks where blocker_id = auth.uid() and blocked_id = target_id;
  select true;
$$;

drop function if exists public.bs_list_friends();
create function public.bs_list_friends()
returns table(
  friend_id uuid,
  username text,
  display_name text,
  avatar text,
  bio text,
  presence_status text,
  is_online boolean,
  last_seen_at timestamptz,
  unread_count bigint
)
language sql
stable
security definer
set search_path = public
as $$
  select
    p.id,
    p.username,
    p.display_name,
    case when p.profile_visibility = 'private' then null else p.avatar end,
    case when p.profile_visibility <> 'private' then p.bio else '' end,
    case when p.show_online_status then p.presence_status else 'hidden' end,
    case when p.show_online_status and p.presence_status <> 'invisible' and p.last_seen_at > now() - interval '2 minutes' then true else false end,
    case when p.show_online_status then p.last_seen_at else null end,
    (select count(*) from public.bs_direct_messages m where m.sender_id = p.id and m.recipient_id = auth.uid() and m.read_at is null)
  from public.bs_friendships f
  join public.bs_profiles p on p.id = case when f.requester_id = auth.uid() then f.addressee_id else f.requester_id end
  where f.status = 'accepted'
    and (f.requester_id = auth.uid() or f.addressee_id = auth.uid())
    and not public.bs_is_blocked(auth.uid(), p.id)
  order by 7 desc, p.display_name asc;
$$;

create or replace function public.bs_list_friend_requests()
returns table(
  request_id bigint,
  direction text,
  user_id uuid,
  username text,
  display_name text,
  avatar text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    f.id,
    case when f.addressee_id = auth.uid() then 'incoming' else 'outgoing' end,
    p.id,
    p.username,
    p.display_name,
    p.avatar,
    f.created_at
  from public.bs_friendships f
  join public.bs_profiles p on p.id = case when f.addressee_id = auth.uid() then f.requester_id else f.addressee_id end
  where f.status='pending'
    and (f.requester_id=auth.uid() or f.addressee_id=auth.uid())
  order by f.created_at desc;
$$;

create or replace function public.bs_list_conversations()
returns table(
  user_id uuid,
  username text,
  display_name text,
  avatar text,
  last_message text,
  last_message_at timestamptz,
  unread_count bigint,
  is_friend boolean,
  presence_status text,
  is_online boolean
)
language sql
stable
security definer
set search_path = public
as $$
  with peers as (
    select distinct case when m.sender_id=auth.uid() then m.recipient_id else m.sender_id end as peer_id
    from public.bs_direct_messages m
    where m.sender_id=auth.uid() or m.recipient_id=auth.uid()
  )
  select
    p.id,
    p.username,
    p.display_name,
    case when p.profile_visibility = 'private' and not public.bs_are_friends(auth.uid(), p.id) then null else p.avatar end,
    latest.text,
    latest.created_at,
    (select count(*) from public.bs_direct_messages u where u.sender_id=p.id and u.recipient_id=auth.uid() and u.read_at is null),
    public.bs_are_friends(auth.uid(), p.id),
    case when p.show_online_status then p.presence_status else 'hidden' end,
    case when p.show_online_status and p.presence_status <> 'invisible' and p.last_seen_at > now() - interval '2 minutes' then true else false end
  from peers x
  join public.bs_profiles p on p.id=x.peer_id
  join lateral (
    select m.text, m.created_at
    from public.bs_direct_messages m
    where (m.sender_id=auth.uid() and m.recipient_id=p.id)
       or (m.sender_id=p.id and m.recipient_id=auth.uid())
    order by m.created_at desc
    limit 1
  ) latest on true
  where not public.bs_is_blocked(auth.uid(), p.id)
  order by latest.created_at desc;
$$;

create or replace function public.bs_list_blocked()
returns table(user_id uuid, username text, display_name text, avatar text, created_at timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  select p.id, p.username, p.display_name, p.avatar, b.created_at
  from public.bs_player_blocks b
  join public.bs_profiles p on p.id=b.blocked_id
  where b.blocker_id=auth.uid()
  order by b.created_at desc;
$$;

create or replace function public.bs_mark_conversation_read(friend_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  affected bigint;
begin
  update public.bs_direct_messages
  set read_at = now()
  where sender_id = friend_id and recipient_id = auth.uid() and read_at is null;
  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace function public.bs_mark_notification_read(notification_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.bs_notifications set read_at=now()
  where id=notification_id and user_id=auth.uid();
  return found;
end;
$$;

create or replace function public.bs_mark_all_notifications_read()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  affected bigint;
begin
  update public.bs_notifications set read_at=now()
  where user_id=auth.uid() and read_at is null;
  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace function public.bs_touch_presence(next_status text default 'online')
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if next_status not in ('online','away','busy','offline','invisible') then next_status := 'online'; end if;
  update public.bs_profiles
  set presence_status = next_status, last_seen_at = now(), updated_at = now()
  where id = auth.uid();
  return found;
end;
$$;

create or replace function public.bs_social_health()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object('ok', true, 'version', '3.6.0');
$$;

create or replace function public.bs_notify_friendship()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and new.status = 'pending' then
    insert into public.bs_notifications(user_id, type, actor_id, payload)
    values(new.addressee_id, 'friend_request', new.requester_id, jsonb_build_object('friendship_id', new.id));
  elsif tg_op = 'UPDATE' and old.status = 'pending' and new.status = 'accepted' then
    insert into public.bs_notifications(user_id, type, actor_id, payload)
    values(new.requester_id, 'friend_accepted', new.addressee_id, jsonb_build_object('friendship_id', new.id));
  end if;
  return new;
end;
$$;

drop trigger if exists bs_friendship_notification_trigger on public.bs_friendships;
create trigger bs_friendship_notification_trigger
after insert or update on public.bs_friendships
for each row execute function public.bs_notify_friendship();

create or replace function public.bs_notify_message()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.bs_notifications(user_id, type, actor_id, payload)
  values(new.recipient_id, 'message', new.sender_id, jsonb_build_object('message_id', new.id));
  return new;
end;
$$;

drop trigger if exists bs_message_notification_trigger on public.bs_direct_messages;
create trigger bs_message_notification_trigger
after insert on public.bs_direct_messages
for each row execute function public.bs_notify_message();

grant execute on function public.bs_search_profiles(text) to authenticated;
grant execute on function public.bs_get_social_profile(uuid) to authenticated;
grant execute on function public.bs_send_friend_request(uuid) to authenticated;
grant execute on function public.bs_respond_friend_request(bigint,text) to authenticated;
grant execute on function public.bs_remove_friend(uuid) to authenticated;
grant execute on function public.bs_block_user(uuid) to authenticated;
grant execute on function public.bs_unblock_user(uuid) to authenticated;
grant execute on function public.bs_list_friends() to authenticated;
grant execute on function public.bs_list_friend_requests() to authenticated;
grant execute on function public.bs_list_conversations() to authenticated;
grant execute on function public.bs_list_blocked() to authenticated;
grant execute on function public.bs_mark_conversation_read(uuid) to authenticated;
grant execute on function public.bs_mark_notification_read(bigint) to authenticated;
grant execute on function public.bs_mark_all_notifications_read() to authenticated;
grant execute on function public.bs_touch_presence(text) to authenticated;
grant execute on function public.bs_social_health() to authenticated;

commit;
