-- Battle Spirits Simulator 2.3 - contas/perfil/amigos/chat/decks
-- Execute no SQL Editor do seu projeto Supabase uma única vez.

create table if not exists public.bs_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (char_length(username) between 3 and 24),
  display_name text not null default 'Jogador',
  bio text not null default '',
  avatar text,
  banner text,
  updated_at timestamptz not null default now()
);

create table if not exists public.bs_friendships (
  id bigint generated by default as identity primary key,
  requester_id uuid not null references public.bs_profiles(id) on delete cascade,
  addressee_id uuid not null references public.bs_profiles(id) on delete cascade,
  status text not null default 'accepted' check (status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(),
  unique(requester_id, addressee_id),
  check (requester_id <> addressee_id)
);

create table if not exists public.bs_direct_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.bs_profiles(id) on delete cascade,
  recipient_id uuid not null references public.bs_profiles(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.bs_player_decks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  decks jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.bs_profiles enable row level security;
alter table public.bs_friendships enable row level security;
alter table public.bs_direct_messages enable row level security;
alter table public.bs_player_decks enable row level security;

drop policy if exists "profiles readable" on public.bs_profiles;
create policy "profiles readable" on public.bs_profiles for select to authenticated using (true);
drop policy if exists "profile owner write" on public.bs_profiles;
create policy "profile owner write" on public.bs_profiles for all to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "friendships visible to participants" on public.bs_friendships;
create policy "friendships visible to participants" on public.bs_friendships for select to authenticated using (auth.uid() = requester_id or auth.uid() = addressee_id);
drop policy if exists "friendship create self" on public.bs_friendships;
create policy "friendship create self" on public.bs_friendships for insert to authenticated with check (auth.uid() = requester_id);
drop policy if exists "friendship participant update" on public.bs_friendships;
create policy "friendship participant update" on public.bs_friendships for update to authenticated using (auth.uid() = requester_id or auth.uid() = addressee_id);

drop policy if exists "messages participants read" on public.bs_direct_messages;
create policy "messages participants read" on public.bs_direct_messages for select to authenticated using (auth.uid() = sender_id or auth.uid() = recipient_id);
drop policy if exists "messages sender insert" on public.bs_direct_messages;
create policy "messages sender insert" on public.bs_direct_messages for insert to authenticated with check (auth.uid() = sender_id);

drop policy if exists "decks owner" on public.bs_player_decks;
create policy "decks owner" on public.bs_player_decks for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.bs_list_friends()
returns table(friend_id uuid, username text, display_name text, avatar text, bio text)
language sql
security invoker
set search_path = public
as $$
  select p.id, p.username, p.display_name, p.avatar, p.bio
  from public.bs_friendships f
  join public.bs_profiles p on p.id = case when f.requester_id = auth.uid() then f.addressee_id else f.requester_id end
  where f.status = 'accepted' and (f.requester_id = auth.uid() or f.addressee_id = auth.uid());
$$;

grant execute on function public.bs_list_friends() to authenticated;
