-- Battle Spirits Eternal Simulator v3.7.0 — Ranked Season 0
begin;

create table if not exists public.bs_ranked_profiles (
  user_id uuid not null references auth.users(id) on delete cascade,
  season text not null default 'S0',
  rp integer not null default 1000 check (rp >= 0),
  peak_rp integer not null default 1000 check (peak_rp >= 0),
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  placements integer not null default 0 check (placements >= 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, season)
);

create table if not exists public.bs_ranked_matches (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  season text not null default 'S0',
  match_uid text not null,
  result text not null check (result in ('win','loss')),
  rp_before integer not null,
  rp_after integer not null,
  rp_delta integer not null,
  opponent_name text,
  opponent_username text,
  end_reason text not null default 'game',
  played_at timestamptz not null default now(),
  unique(user_id, match_uid)
);

create index if not exists bs_ranked_matches_user_played_idx
  on public.bs_ranked_matches(user_id, season, played_at desc);

alter table public.bs_ranked_profiles enable row level security;
alter table public.bs_ranked_matches enable row level security;

drop policy if exists ranked_profile_read_own on public.bs_ranked_profiles;
create policy ranked_profile_read_own on public.bs_ranked_profiles
for select to authenticated using (auth.uid() = user_id);

drop policy if exists ranked_match_read_own on public.bs_ranked_matches;
create policy ranked_match_read_own on public.bs_ranked_matches
for select to authenticated using (auth.uid() = user_id);

-- Escrita competitiva fica deliberadamente sem policy para authenticated.
-- O servidor Online usa SUPABASE_SERVICE_ROLE_KEY e é o único responsável
-- por criar/alterar RP e inserir resultados Ranked.

create or replace function public.bs_ranked_settle_match(
  p_match_uid text,
  p_season text,
  p_winner_id uuid,
  p_loser_id uuid,
  p_winner_before integer,
  p_loser_before integer,
  p_winner_delta integer,
  p_loser_delta integer,
  p_winner_name text,
  p_winner_username text,
  p_loser_name text,
  p_loser_username text,
  p_reason text default 'game'
) returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_winner_after integer := greatest(0, p_winner_before + p_winner_delta);
  v_loser_after integer := greatest(0, p_loser_before + p_loser_delta);
begin
  if p_winner_id is null or p_loser_id is null or p_winner_id = p_loser_id then
    raise exception 'invalid ranked players';
  end if;
  if coalesce(trim(p_match_uid), '') = '' then raise exception 'match uid required'; end if;

  insert into public.bs_ranked_profiles(user_id, season, rp, peak_rp, wins, losses, placements, updated_at)
  values (p_winner_id, p_season, v_winner_after, greatest(p_winner_before, v_winner_after), 1, 0, 0, now())
  on conflict (user_id, season) do update set
    rp = v_winner_after, peak_rp = greatest(bs_ranked_profiles.peak_rp, v_winner_after),
    wins = bs_ranked_profiles.wins + 1, updated_at = now();

  insert into public.bs_ranked_profiles(user_id, season, rp, peak_rp, wins, losses, placements, updated_at)
  values (p_loser_id, p_season, v_loser_after, greatest(p_loser_before, v_loser_after), 0, 1, 0, now())
  on conflict (user_id, season) do update set
    rp = v_loser_after, peak_rp = greatest(bs_ranked_profiles.peak_rp, v_loser_after),
    losses = bs_ranked_profiles.losses + 1, updated_at = now();

  insert into public.bs_ranked_matches(user_id, season, match_uid, result, rp_before, rp_after, rp_delta, opponent_name, opponent_username, end_reason, played_at)
  values
    (p_winner_id, p_season, p_match_uid, 'win', p_winner_before, v_winner_after, p_winner_delta, p_loser_name, p_loser_username, p_reason, now()),
    (p_loser_id, p_season, p_match_uid, 'loss', p_loser_before, v_loser_after, p_loser_delta, p_winner_name, p_winner_username, p_reason, now())
  on conflict (user_id, match_uid) do nothing;
end;
$$;

revoke all on function public.bs_ranked_settle_match(text,text,uuid,uuid,integer,integer,integer,integer,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.bs_ranked_settle_match(text,text,uuid,uuid,integer,integer,integer,integer,text,text,text,text,text) to service_role;

create or replace function public.bs_social_health()
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object('ok', true, 'version', '3.7.0');
$$;

grant select on public.bs_ranked_profiles to authenticated;
grant select on public.bs_ranked_matches to authenticated;
grant execute on function public.bs_social_health() to authenticated;

commit;
