import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { normalizeCard, makeCardIndex } from '../cardAdapter.js';
import { makePhysicalCard } from '../state.js';
import { resolveActionList } from './actionResolver.js';
import { conditionMatchesEffect } from './conditionEngine.js';
import { listSupportedCoreActionTypes } from './coreActionLibrary.js';

const raw=JSON.parse(fs.readFileSync(new URL('../../data/cards.json',import.meta.url),'utf8'));
const cards=(Array.isArray(raw)?raw:raw.cards).map(normalizeCard); const index=makeCardIndex(cards);
const get=(id)=>cards.find(c=>c.id===id&&c.set==='BSC49'); const ability=(id,aid)=>get(id).abilities.find(a=>a.id===aid);
function physical(id,instance,regular=2,exhausted=false){return {...makePhysicalCard(id,index),instanceId:instance,cores:{regular,soul:false},exhausted};}
function base(){return {turnPlayerId:'player1',activePlayerId:'player1',phase:'attack',players:{player1:{id:'player1',life:5,reserve:12,trashCores:0,soulCore:{zone:'reserve',instanceId:null},hand:[],deck:[],trash:[],revealed:[],openArea:[],removed:[],field:{spirits:[],nexuses:[],other:[]},burst:null},player2:{id:'player2',life:5,reserve:12,trashCores:0,soulCore:{zone:'reserve',instanceId:null},hand:[],deck:[],trash:[],revealed:[],openArea:[],removed:[],field:{spirits:[],nexuses:[],other:[]},burst:null}},temporary:{}};}

test('batch23 keeps Core Action Library stable',()=>assert.equal(listSupportedCoreActionTypes().length,83));
test('batch23 coverage advances BSC49 to 84 resolved and global fallback below ten percent',()=>{const c=JSON.parse(fs.readFileSync(new URL('../../../data/effect-coverage-v5.1.0-content-batch23.json',import.meta.url),'utf8'));const r=c.cards.filter(x=>x.set==='BSC49');assert.equal(r.filter(x=>['AUTOMATED','NO_EFFECT'].includes(x.status)).length,84);assert.equal(r.filter(x=>!['AUTOMATED','NO_EFFECT'].includes(x.status)).length,33);const unresolved=c.cards.filter(x=>!['AUTOMATED','NO_EFFECT'].includes(x.status)).length;assert.equal(unresolved,33);assert.ok((unresolved/c.cards.length*100)<10);});
test('Dragonaga-adjacent direct cluster: Siberza structures first attack Open Area and refresh',()=>{assert.equal(ability('BSC49-021','bsc49-021-first-blade-attack-auto43').actions[0].onSelect.toZone,'openArea');assert.equal(ability('BSC49-021','bsc49-021-first-self-refresh-auto43').actions[0].type,'refresh');});
test('Kigna-Swan structures attack-step Flash, deck lock and exhaustion Core recovery',()=>{assert.equal(ability('BSC49-029','bsc49-029-flash-auto43').actions[1].property,'bp');assert.equal(ability('BSC49-029','bsc49-029-deck-lock-auto43').actions[0].value,0);});
test('Tiael uses bottom-deck draw and Trash-symbol reduction',()=>{assert.equal(ability('BSC49-041','bsc49-041-summon-draw-auto43').actions[0].yesActions[0].from,'bottom');assert.equal(ability('BSC49-041','bsc49-041-trash-reduction-auto43').actions[0].property,'trashSymbolsCountForSummonReduction');});
test('draw action supports the bottom of the deck generically',()=>{let m=base();m.players.player1.deck=[physical('BSC49-001','top'),physical('BSC49-002','bottom')];const r=resolveActionList(m,[{type:'draw',count:1,from:'bottom'}],index,{sourcePlayerId:'player1'});assert.equal(r.match.players.player1.hand[0].instanceId,'bottom');assert.equal(r.match.players.player1.deck[0].instanceId,'top');});
test('Trickster structures Burst, summon choice and attack/block refresh',()=>{assert.equal(ability('BSC49-042','bsc49-042-burst-auto43').actions[0].type,'specialSummonSource');assert.equal(ability('BSC49-042','bsc49-042-summon-choice-auto43').actions[0].type,'chooseOption');});
test('Venu-Feather LT reuses established remain-on-field and Braved blocked Life semantics',()=>{assert.equal(ability('BSC49-043','bsc49-043-remain-auto43').actions[1].exhausted,true);assert.equal(ability('BSC49-043','bsc49-043-braved-blocked-life-auto43').actions[0].countFromSourceSymbols,true);});
test('Shining Galaxy structures Trash recovery, cost override and battle buff',()=>{assert.equal(ability('BSC49-075','bsc49-075-cost-auto43').actions[0].value,5);assert.equal(ability('BSC49-075','bsc49-075-flash-auto43').actions[2].onSelect[0].type,'modifyBP');});
test('Freezing Lake structures alternate deploy, deck cap and opponent hand observer',()=>{assert.equal(ability('BSC49-078','bsc49-078-deck-cap-auto43').actions[0].value,6);assert.equal(ability('BSC49-078','bsc49-078-opponent-hand-auto43').conditions[2].type,'eventMovedByEffect');});
test('Flower Garden structures Yellow Trash reduction and Main Step Life conversion',()=>{assert.equal(ability('BSC49-080','bsc49-080-trash-reduction-auto43').actions[0].property,'trashSymbolsCountForYellowSummonReduction');assert.equal(ability('BSC49-080','bsc49-080-main-life-auto43').actions[0].type,'oncePerTurn');});
test('Ancient Battleship Sail structures Burst destruction/deploy and summon cap',()=>{assert.equal(ability('BSC49-084','bsc49-084-burst-auto43').actions[0].onSelect.type,'destroy');assert.equal(ability('BSC49-084','bsc49-084-summon-limit-auto43').actions[0].value,1);});
test('Brave Draw structures conditional cost, Main reveal routing and Braved BP Flash',()=>{assert.equal(ability('BSC49-088','bsc49-088-main-auto43').actions[1].matchSelector.cardTypes[0],'brave');assert.equal(ability('BSC49-088','bsc49-088-flash-auto43').actions[0].onSelect.amount,10000);});
test('Sagitta Flame structures protection/recovery and both Flash destruction branches',()=>{assert.equal(ability('BSC49-089','bsc49-089-trash-recover-auto43').conditions[0].type,'eventSourceBraved');assert.equal(ability('BSC49-089','bsc49-089-flash-auto43').actions[1].options.length,2);});
test('Totentanz LT structures Brave-triggered Trash recovery and two-Core Flash removal',()=>{assert.equal(ability('BSC49-090','bsc49-090-trash-recover-auto43').conditions[0].cardType,'brave');assert.equal(ability('BSC49-090','bsc49-090-flash-auto43').actions[1].amount,2);});
test('new generic conditions are runtime-evaluable',()=>{let m=base();m.players.player1.field.spirits=[physical('BSC49-021','s1')];const ctx={sourcePlayerId:'player1',sourceInstanceId:'s1',sourcePhysical:m.players.player1.field.spirits[0],sourceCard:get('BSC49-021'),eventSourceInstanceId:'s1'};assert.equal(conditionMatchesEffect(m,{type:'controlsNameIncludes',text:'Spearhead'},ctx,index),true);assert.equal(conditionMatchesEffect(m,{type:'eventSourceBraved'},ctx,index),false);});
