import test from 'node:test'; import assert from 'node:assert/strict'; import fs from 'node:fs';
import { normalizeCard, makeCardIndex } from '../cardAdapter.js'; import { dispatchEffectEvent } from './triggerDispatcher.js'; import { resolveActionList } from './actionResolver.js'; import { getContinuousPlayerNumericModifier } from './modifierResolver.js';
const raw=JSON.parse(fs.readFileSync(new URL('../../data/cards.json',import.meta.url),'utf8')); const cards=(Array.isArray(raw)?raw:raw.cards).map(normalizeCard); const index=makeCardIndex(cards); const get=id=>cards.find(c=>c.id===id); const ability=(id,aid)=>get(id).abilities.find(a=>a.id===aid); const physical=(cardId,instanceId,cores=0,exhausted=false)=>({cardId,instanceId,cores:{regular:cores,soul:false},exhausted,combinedWith:null,flags:{}});
function base(){return {turnNumber:10,activePlayerId:'player1',firstPlayerId:'player2',phase:'attack',players:{player1:{id:'player1',life:4,reserve:10,trashCores:0,soulCore:{zone:'reserve',instanceId:null},hand:[],deck:[],trash:[],revealed:[],openArea:[],removed:[],field:{spirits:[],nexuses:[],other:[]},burst:null,turnFlags:{}},player2:{id:'player2',life:5,reserve:10,trashCores:0,soulCore:{zone:'reserve',instanceId:null},hand:[],deck:[],trash:[],revealed:[],openArea:[],removed:[],field:{spirits:[],nexuses:[],other:[]},burst:null,turnFlags:{}}},temporary:{},persistentEffects:{}};}
test('XV03 has four structured abilities',()=>{for(const id of ['bsc49-xv03-burst-auto54','bsc49-xv03-recovery-auto54','bsc49-xv03-core-remove-auto54','bsc49-xv03-replacement-auto54'])assert.ok(ability('BSC49-XV03',id));});
test('controllerBurst observer summons Stein-Bolg after own Life decreases',()=>{let m=base();m.players.player1.burst={...physical('BSC49-XV03','burst'),faceDown:true};const r=dispatchEffectEvent(m,{event:'lifeDecreased',sourcePlayerId:'player2',eventPlayerId:'player1',context:{eventPlayerId:'player1'}},index);assert.ok(r.match.players.player1.field.spirits.some(x=>x.instanceId==='burst'));assert.equal(r.match.players.player1.burst,null);});
test('Stein-Bolg recovers a Purple card on summon',()=>{let m=base();const s=physical('BSC49-XV03','stein',1);m.players.player1.field.spirits=[s];m.players.player1.trash=[physical('BSC49-056','purple')];const a=ability('BSC49-XV03','bsc49-xv03-recovery-auto54');const r=resolveActionList(m,a.actions,index,{sourcePlayerId:'player1',sourceInstanceId:'stein',sourcePhysical:s,sourceCard:get('BSC49-XV03')});assert.ok(r.match.players.player1.hand.some(x=>x.instanceId==='purple'));});
test('Lv2 replacement redirects opponent core removal from Reserve to Trash',()=>{let m=base();const s=physical('BSC49-XV03','stein',3);const target=physical('BSC49-004','target',2);m.players.player1.field.spirits=[s];m.players.player2.field.spirits=[target];m=resolveActionList(m,ability('BSC49-XV03','bsc49-xv03-replacement-auto54').actions,index,{sourcePlayerId:'player1',sourceInstanceId:'stein',sourcePhysical:s,sourceCard:get('BSC49-XV03')}).match;assert.equal(getContinuousPlayerNumericModifier(m,'player1','opponentEffectCoreToTrash'),1);m=resolveActionList(m,[{type:'removeCore',amount:1,destination:'reserve',selector:{owner:'opponent',zones:['field'],instanceId:'target'}}],index,{sourcePlayerId:'player1',sourceInstanceId:'stein',sourcePhysical:s,sourceCard:get('BSC49-XV03')}).match;assert.equal(m.players.player2.reserve,10);assert.equal(m.players.player2.trashCores,1);});
test('attack observer accepts Astral Soul or Galaxian event sources',()=>{const a=ability('BSC49-XV03','bsc49-xv03-core-remove-auto54');assert.equal(a.conditions[0].type,'eventSourceFamilyAny');assert.deepEqual(a.conditions[0].families,['Astral Soul','Galaxian']);});
