import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { normalizeCard, makeCardIndex } from '../cardAdapter.js';
import { createMatch, makePhysicalCard } from '../state.js';
import { dispatchEffectEvent } from './triggerDispatcher.js';
import { resolveActionList } from './actionResolver.js';
import { listSupportedCoreActionTypes } from './coreActionLibrary.js';
import { getContinuousPlayerNumericModifier } from './modifierResolver.js';
import { summonFromHand } from '../summon.js';
import { combineBrave } from '../brave.js';

const rawCards=JSON.parse(fs.readFileSync(new URL('../../data/cards.json',import.meta.url),'utf8'));
const normalized=rawCards.map(normalizeCard); const index=makeCardIndex(normalized); const byId=new Map(normalized.map(c=>[String(c.id),c]));
const deck=Array.from({length:40},()=> 'BS13-001');
function base(){const m=createMatch({player1:{name:'A',deck},player2:{name:'B',deck},firstPlayerId:'player1',cardIndex:index,random:()=>0.25});m.turnNumber=2;m.phase='main';m.activePlayerId='player1';m.players.player1.reserve=30;m.players.player2.reserve=30;return m;}
function physical(id,instance,cores=2,exhausted=false,combinedWith=null){return {...makePhysicalCard(id,index),instanceId:instance,cores:{regular:cores,soul:false},exhausted,combinedWith};}
function ability(id,a){return byId.get(id)?.abilities?.find(x=>x.id===a);}

test('content batch 14: BS13 Wave 6 resolves ten more cards and leaves 10 pending',()=>{const cov=JSON.parse(fs.readFileSync(new URL('../../../data/effect-coverage.json',import.meta.url),'utf8'));const rows=cov.cards.filter(x=>x.set==='BS13');assert.equal(rows.length,90);assert.equal(rows.filter(x=>!['AUTOMATED','NO_EFFECT'].includes(x.status)).length,10);assert.equal(rows.filter(x=>['AUTOMATED','NO_EFFECT'].includes(x.status)).length,80);});

test('content batch 14: Core Action Library exposes field-combine and event-source recovery actions',()=>{const types=listSupportedCoreActionTypes();for(const t of ['combineBraveFromField','returnEventSourceToHand'])assert.equal(types.includes(t),true);assert.ok(types.length>=77);});

test('content batch 14: Pandolancer can combine a Brave in Spirit form while attacking',()=>{let m=base();m.phase='attack';const host=physical('BS13-007','host',4,false);const brave=physical('BS13-053','brave',1,false);m.players.player1.field.spirits=[host];m.players.player1.field.other=[brave];const a=ability('BS13-007','bs13-007-attack-combine-auto34');const r=resolveActionList(m,a.actions,index,{sourcePlayerId:'player1',sourceInstanceId:'host',sourcePhysical:host,sourceCard:byId.get('BS13-007'),bravedReplay:false});assert.equal(r.match.players.player1.field.other[0].combinedWith,'host');});

test('content batch 14: Megalo-Saur exposes a dynamic combined-BP destruction budget',()=>{let m=base();const src=physical('BS13-008','mega',3);const dragon=physical('BS13-014','dragon',2);m.players.player1.field.spirits=[src,dragon];m.players.player2.field.spirits=[physical('BS13-001','opp1',1),physical('BS13-002','opp2',1)];const a=ability('BS13-008','bs13-008-summon-destroy-budget-auto34');const r=resolveActionList(m,a.actions,index,{sourcePlayerId:'player1',sourceInstanceId:'mega',sourcePhysical:src,sourceCard:byId.get('BS13-008')});assert.equal(r.manualResolutionNeeded,true);assert.ok(Number(r.decision?.maxTotalBP||0)>=9000);});

test('content batch 14: Mokubaoh can refresh and combine with a newly summoned High Speed Spirit',()=>{let m=base();const brave=physical('BS13-053','mokuba',1,true);const high=physical('BS13-021','speed',1,false);m.players.player1.field.other=[brave];m.players.player1.field.spirits=[high];const a=ability('BS13-053','bs13-053-highspeed-combine-auto34');const r=resolveActionList(m,a.actions,index,{sourcePlayerId:'player1',sourceInstanceId:'mokuba',sourcePhysical:brave,sourceCard:byId.get('BS13-053'),eventSourceInstanceId:'speed'});const placed=r.match.players.player1.field.other.find(x=>x.instanceId==='mokuba');assert.equal(placed.combinedWith,'speed');assert.equal(placed.exhausted,false);});

test('content batch 14: Poppor survives host destruction as a refreshed Brave in Spirit form',()=>{let m=base();const host=physical('BS13-008','host',3,false);const brave=physical('BS13-057','poppor',0,true,'host');m.players.player1.field.spirits=[host];m.players.player1.field.other=[brave];m=dispatchEffectEvent(m,{event:'continuous',sourcePlayerId:'player1',sourceInstanceId:'poppor',eventPlayerId:'player1'},index).match;const r=resolveActionList(m,[{type:'destroy',instanceId:'host'}],index,{sourcePlayerId:'player2',sourceInstanceId:'enemy',sourceCard:{id:'SYN',cardType:'spirit',colors:['red']}});const surviving=r.match.players.player1.field.other.find(x=>x.instanceId==='poppor');assert.ok(surviving);assert.equal(surviving.combinedWith,null);assert.equal(surviving.exhausted,false);assert.equal(surviving.flags?.lastCombinedWith,'host');});

test('content batch 14: Tres-Beluga refreshes its host when the six-card mill includes a Galaxian',()=>{let m=base();const host=physical('BS13-008','host',3,true);const brave=physical('BS13-060','beluga',0,true,'host');m.players.player1.field.spirits=[host];m.players.player1.field.other=[brave];m.players.player1.deck=[physical('BS13-X01','g1'),...Array.from({length:5},(_,i)=>physical('BS13-001',`d${i}`)),...m.players.player1.deck];const a=ability('BS13-060','bs13-060-braved-attack-mill-auto34');const yes=a.actions[0].yesActions;const r=resolveActionList(m,yes,index,{sourcePlayerId:'player1',sourceInstanceId:'beluga',sourcePhysical:brave,sourceCard:byId.get('BS13-060'),eventSourceInstanceId:'host'});assert.equal(r.match.players.player1.field.spirits[0].exhausted,false);assert.ok(r.match.players.player1.trash.some(x=>x.instanceId==='g1'));});

test('content batch 14: Palace of Snake Believers registers both player-level battle modifiers',()=>{let m=base();const nx=physical('BS13-064','palace',1);m.players.player1.field.nexuses=[nx];m=dispatchEffectEvent(m,{event:'continuous',sourcePlayerId:'player1',sourceInstanceId:'palace',eventPlayerId:'player1'},index).match;assert.equal(getContinuousPlayerNumericModifier(m,'player1','darkSnakeAttackLifeToVoid'),1);assert.equal(getContinuousPlayerNumericModifier(m,'player1','opponentAttackLifeDiscardPerSymbol'),1);});

test('content batch 14: Vanishing Day replaces effect returns to hand with top-deck placement',()=>{let m=base();const magic=byId.get('BS13-079');const main=ability('BS13-079','bs13-079-main-return-replacement-auto34');m=resolveActionList(m,main.actions,index,{sourcePlayerId:'player1',sourceInstanceId:'magic',sourceCard:magic}).match;const target=physical('BS13-001','opp',1);m.players.player2.field.spirits=[target];const r=resolveActionList(m,[{type:'returnToHand',instanceId:'opp'}],index,{sourcePlayerId:'player1',sourceInstanceId:'magic',sourceCard:magic});assert.equal(r.match.players.player2.hand.some(x=>x.instanceId==='opp'),false);assert.equal(r.match.players.player2.deck[0]?.instanceId,'opp');});

test('content batch 14: Sephiro-Aries forces non-Imp Main Step summons to enter exhausted',()=>{let m=base();const aries=physical('BS13-X03','aries',4);m.players.player1.field.spirits=[aries];m=dispatchEffectEvent(m,{event:'continuous',sourcePlayerId:'player1',sourceInstanceId:'aries',eventPlayerId:'player1'},index).match;m.activePlayerId='player2';m.phase='main';const hand=physical('BS13-001','summon-me',0);m.players.player2.hand=[hand];m.players.player2.reserve=20;const r=summonFromHand(m,'player2','summon-me',index,{coresToPlace:1});assert.equal(r.ok,true);assert.equal(r.match.players.player2.field.spirits.find(x=>x.instanceId==='summon-me')?.exhausted,true);});

test('content batch 14: Rean ignores a Brave combine condition while its continuous effect is active',()=>{let m=base();const rean=physical('BS13-X05','rean',2);const brave=physical('BS13-053','brave',1);m.players.player1.field.spirits=[rean];m.players.player1.field.other=[brave];m=dispatchEffectEvent(m,{event:'continuous',sourcePlayerId:'player1',sourceInstanceId:'rean',eventPlayerId:'player1'},index).match;const r=combineBrave(m,'player1','brave','rean',index);assert.equal(r.ok,true);assert.equal(r.match.players.player1.field.other.find(x=>x.instanceId==='brave')?.combinedWith,'rean');});
