import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { normalizeCard, makeCardIndex } from '../cardAdapter.js';
import { makePhysicalCard } from '../state.js';
import { resolveActionList } from './actionResolver.js';
import { listSupportedCoreActionTypes } from './coreActionLibrary.js';

const raw=JSON.parse(fs.readFileSync(new URL('../../data/cards.json',import.meta.url),'utf8'));
const cards=(Array.isArray(raw)?raw:raw.cards).map(normalizeCard);
const index=makeCardIndex(cards);
const get=(id)=>cards.find(c=>c.id===id&&c.set==='BSC49');
const ability=(id,aid)=>get(id).abilities.find(a=>a.id===aid);
function physical(id,instance,regular=2,exhausted=false){return {...makePhysicalCard(id,index),instanceId:instance,cores:{regular,soul:false},exhausted};}
function base(){return {turnPlayerId:'player1',activePlayerId:'player1',phase:'attack',players:{player1:{id:'player1',life:5,reserve:12,trashCores:0,soulCore:{zone:'reserve',instanceId:null},hand:[],deck:[],trash:[],revealed:[],openArea:[],removed:[],field:{spirits:[],nexuses:[],other:[]},burst:null},player2:{id:'player2',life:5,reserve:12,trashCores:0,soulCore:{zone:'reserve',instanceId:null},hand:[],deck:[],trash:[],revealed:[],openArea:[],removed:[],field:{spirits:[],nexuses:[],other:[]},burst:null}},temporary:{}};}

test('content batch 21 keeps the generic Core Action Library stable',()=>{const t=listSupportedCoreActionTypes();assert.equal(t.length>=83,true);for(const x of ['paySourceCost','specialSummonSource','returnEventSourceToHand','moveLifeToReserve'])assert.equal(t.includes(x),true);});
test('content batch 21: Bal-Gunner LT recovers from deck-to-Trash and structures attack destruction/draw',()=>{const r=ability('BSC49-052','bsc49-052-trash-recover-auto41');const a=ability('BSC49-052','bsc49-052-combined-attack-auto41');assert.equal(r.trigger.event,'cardMoved');assert.equal(a.actions[0].selector.maximumBP,6000);assert.equal(a.actions[1].type,'draw');});
test('content batch 21: Amphisbaenar LT structures summon removal and family combine condition',()=>{const a=ability('BSC49-053','bsc49-053-summon-auto41');const c=ability('BSC49-053','bsc49-053-combine-auto41');assert.equal(a.actions[0].selector.maximumBP,10000);assert.deepEqual(c.combineCondition.families,['Concluser','Astral Soul','Divine Star','Galaxian']);});
test('content batch 21: Shine-Blazer LT exposes paid hand summon and Life pressure observer',()=>{const h=ability('BSC49-054','bsc49-054-hand-summon-auto41');const l=ability('BSC49-054','bsc49-054-life-pressure-auto41');assert.equal(h.actions[0].actions[0].yesActions[0].type,'paySourceCost');assert.equal(l.actions[0].yesActions[0].type,'moveLifeToReserve');});
test('content batch 21: Phoenix-Cannon LT routes reveal choice and two-target summon destruction',()=>{const r=ability('BSC49-055','bsc49-055-reveal-auto41');const s=ability('BSC49-055','bsc49-055-summon-auto41');assert.equal(r.actions[0].actions[0].type,'chooseOption');assert.equal(s.actions[0].type,'selectMultipleTargets');assert.equal(s.actions[0].max,2);});
test('content batch 21: Evil-Fisher LT reuses reveal routing and Trash recovery',()=>{const s=ability('BSC49-057','bsc49-057-summon-auto41');const a=ability('BSC49-057','bsc49-057-attack-auto41');assert.equal(s.actions[0].yesActions[0].type,'revealTopAndRoute');assert.equal(a.actions[0].selector.maximumCost,6);});
test('content batch 21: Pendragon LT exposes Trash summon, field core drain, and combined symbol gain',()=>{const t=ability('BSC49-060','bsc49-060-trash-summon-auto41');const s=ability('BSC49-060','bsc49-060-summon-auto41');const a=ability('BSC49-060','bsc49-060-attack-auto41');assert.equal(t.trigger.scope,'controllerTrash');assert.equal(s.actions[0].type,'removeCore');assert.equal(a.actions[1].then[0].type,'modifySymbols');});
test('content batch 21: Shieldybug LT refreshes its combined host after winning BP comparison',()=>{const a=ability('BSC49-061','bsc49-061-attack-auto41');assert.equal(a.trigger.event,'afterBattleResolution');assert.equal(a.actions[0].target,'combinedHost');});
test('content batch 21: Janome-Shielder LT structures burst summon, refresh lock and Brave/Nexus immunity',()=>{const b=ability('BSC49-065','bsc49-065-burst-auto41');const s=ability('BSC49-065','bsc49-065-summon-auto41');const i=ability('BSC49-065','bsc49-065-immunity-auto41');assert.equal(b.actions[0].type,'specialSummonSource');assert.equal(s.actions[0].onSelect.property,'cannotRefresh');assert.deepEqual(i.actions[0].value,['brave','nexus']);});
test('content batch 21: Kumattar LT suppresses exhausted Nexus effects and models Sacred Life',()=>{const a=ability('BSC49-069','bsc49-069-attack-auto41');const l=ability('BSC49-069','bsc49-069-sacred-life-auto41');assert.equal(a.actions[1].property,'exhaustedNexusEffectsSuppressed');assert.equal(l.actions[0].type,'addCoreFromVoid');});
test('content batch 21: Tres-Beluga LT structures Galaxian combine and six-card self mill attack',()=>{const c=ability('BSC49-074','bsc49-074-combine-auto41');const a=ability('BSC49-074','bsc49-074-attack-auto41');assert.deepEqual(c.combineCondition.families,['Galaxian']);assert.equal(a.actions[0].type,'topDeckToTrash');assert.equal(a.actions[0].count,6);});
test('content batch 21: a simple Bal-Gunner attack action resolves destruction and draw',()=>{let m=base();const src=physical('BSC49-052','src');const victim=physical('BSC49-001','victim');m.players.player1.field.spirits=[src];m.players.player2.field.spirits=[victim];m.players.player1.deck=[physical('BSC49-001','draw')];const a=ability('BSC49-052','bsc49-052-combined-attack-auto41');const r=resolveActionList(m,a.actions,index,{sourcePlayerId:'player1',sourceInstanceId:'src',sourcePhysical:src,sourceCard:get('BSC49-052'),selectedTargets:['victim']});assert.equal(r.manualResolutionNeeded,false);});
