const ACTION_ALIASES = Object.freeze({
  modifybp: "modifyBP",
  temporarybp: "modifyBP",
  bpmodifier: "modifyBP",
  gainbp: "modifyBP",
  reducebp: "modifyBP",
  reservecorefromvoid: "addCoreToReserveFromVoid",
  voidtoreserve: "addCoreToReserveFromVoid",
  addcorefromvoid: "addCoreFromVoid",
  addcore: "addCore",
  removecore: "removeCore",
  movecore: "moveCore",
  movecoreselectedtosource: "moveCoreSelectedToSource",
  movecoretolife: "moveCoreToLife",
  paysourcecost: "paySourceCost",
  payaccelcost: "payAccelCost",
  performadvent: "performAdvent",
  specialsummonselected: "specialSummonSelected",
  revealuntilandsummon: "revealUntilAndSummon",
  returnhand: "returnToHand",
  returntohand: "returnToHand",
  returntodeck: "returnToDeck",
  returntobottomdeck: "returnToBottomDeck",
  returnallmatchingtohand: "returnAllMatchingToHand",
  destroyallmatching: "destroyAllMatching",
  refreshallmatching: "refreshAllMatching",
  exhaustallmatching: "exhaustAllMatching",
  topdecktotrash: "topDeckToTrash",
  milldeck: "topDeckToTrash",
  revealtop: "revealTop",
  adjustlife: "adjustLife",
  heallife: "healLife",
  deallifedamage: "dealLifeDamage",
  movelifetoreserve: "moveLifeToReserve",
  selecttarget: "selectTarget",
  selecttrashtarget: "selectTrashTarget",
  selectmultipletargets: "selectMultipleTargets",
  chooseoption: "chooseOption",
  chooseyesno: "chooseYesNo",
  choosecardsfromhand: "chooseCardsFromHand",
  choosecardsfromtrash: "chooseCardsFromTrash",
  choosecardsfromdeck: "chooseCardsFromDeck",
  chooseorder: "chooseOrder",
  choosecoredistribution: "chooseCoreDistribution",
  conditional: "conditional",
  setbattlerestriction: "setBattleRestriction",
  setbattleflag: "setBattleRestriction",
  preventspiritblock: "setBattleRestriction",
  cannotbeblockedbyspirits: "setBattleRestriction",
  cannotbeblockedbylowerlevel: "setBattleRestriction",
  returntotopdeck: "returnToTopDeck",
  returnalltrashmatchingtohand: "returnAllTrashMatchingToHand",
  movelifetotrash: "moveLifeToTrash",
  negateultimatetrigger: "negateUltimateTrigger",
  setturnprotection: "setTurnProtection",
  discardopponentsetburst: "discardOpponentSetBurst",
  performspecifiedattack: "performSpecifiedAttack",
  trimcoresonmatching: "trimCoresOnMatching",
  scheduleattackstependafterbattle: "scheduleAttackStepEndAfterBattle",
  specialsummonfromhand: "specialSummonFromHand",
  specialsummonfromtrash: "specialSummonFromTrash",
  specialsummonsource: "specialSummonSource",
  deployfromtrash: "deployFromTrash",
  forcelevel: "forceLevel",
  requireattackifable: "requireAttackIfAble",
  emitsourceevent: "emitSourceEvent",
  dispatchsourceevent: "dispatchSourceEvent",
  revealtopandroute: "revealTopAndRoute",
  revealtopandsummonorhand: "revealTopAndSummonOrHand",
  onceperturn: "oncePerTurn",
  returnmagicusedthisbattle: "returnMagicUsedThisBattle",
  returnultimatetriggerrevealedmatchingtohand: "returnUltimateTriggerRevealedMatchingToHand",
  swapexhaustionstate: "swapExhaustionState",
  discard: "discard",
  movecard: "moveCard",
  movesourcetoopenarea: "moveSourceToOpenArea",
  placesourceinfield: "placeSourceInField",
  modifycost: "modifyCost",
  modifysymbols: "modifySymbols",
  gainkeyword: "gainKeyword",
  losekeyword: "loseKeyword",
  addmodifier: "addModifier",
  registermodifier: "addModifier",
  removemodifier: "removeModifier",
  preventevent: "preventEvent",
  replaceevent: "replaceEvent",
  replacedesctruction: "replaceEvent",
  replacedestruction: "replaceEvent",
  endcurrentstep: "endCurrentStep",
  uptontimesperturn: "upToNTimesPerTurn",
  specialsummonbravecombinedfromhand: "specialSummonBraveCombinedFromHand",
  specialsummoneventsourcefromtrash: "specialSummonEventSourceFromTrash",
  combinebravefromfield: "combineBraveFromField",
  returneventsourcetohand: "returnEventSourceToHand",
  suppresswhensummonedforendsteps: "suppressWhenSummonedForEndSteps"
});

export const CoreActionType = Object.freeze({
  DRAW: "draw",
  DISCARD: "discard",
  DESTROY: "destroy",
  EXHAUST: "exhaust",
  REFRESH: "refresh",
  MOVE_CARD: "moveCard",
  RETURN_TO_HAND: "returnToHand",
  RETURN_TO_DECK: "returnToDeck",
  RETURN_TO_TOP_DECK: "returnToTopDeck",
  RETURN_TO_BOTTOM_DECK: "returnToBottomDeck",
  ADD_CORE_TO_RESERVE_FROM_VOID: "addCoreToReserveFromVoid",
  ADD_CORE_FROM_VOID: "addCoreFromVoid",
  ADD_CORE: "addCore",
  REMOVE_CORE: "removeCore",
  MOVE_CORE: "moveCore",
  MOVE_CORE_SELECTED_TO_SOURCE: "moveCoreSelectedToSource",
  MOVE_CORE_TO_LIFE: "moveCoreToLife",
  PAY_SOURCE_COST: "paySourceCost",
  ADJUST_LIFE: "adjustLife",
  HEAL_LIFE: "healLife",
  DEAL_LIFE_DAMAGE: "dealLifeDamage",
  MOVE_LIFE_TO_RESERVE: "moveLifeToReserve",
  MOVE_LIFE_TO_TRASH: "moveLifeToTrash",
  MODIFY_BP: "modifyBP",
  MODIFY_COST: "modifyCost",
  MODIFY_SYMBOLS: "modifySymbols",
  GAIN_KEYWORD: "gainKeyword",
  LOSE_KEYWORD: "loseKeyword",
  ADD_MODIFIER: "addModifier",
  REMOVE_MODIFIER: "removeModifier",
  PREVENT_EVENT: "preventEvent",
  REPLACE_EVENT: "replaceEvent"
});

const SUPPORTED_ACTION_TYPES = new Set([
  "draw",
  "discard",
  "moveCard",
  "moveSourceToOpenArea",
  "placeSourceInField",
  "returnToDeck",
  "returnToBottomDeck",
  "addCoreToReserveFromVoid",
  "addCoreToTrashFromVoid",
  "addCoreFromVoid",
  "addCore",
  "removeCore",
  "moveCore",
  "moveCoreSelectedToSource",
  "moveCoreToLife",
  "paySourceCost",
  "payAccelCost",
  "performAdvent",
  "specialSummonSelected",
  "revealUntilAndSummon",
  "adjustLife",
  "healLife",
  "dealLifeDamage",
  "moveLifeToReserve",
  "moveLifeToTrash",
  "negateUltimateTrigger",
  "returnAllTrashMatchingToHand",
  "modifyBP",
  "modifyCost",
  "modifySymbols",
  "gainKeyword",
  "loseKeyword",
  "addModifier",
  "removeModifier",
  "preventEvent",
  "replaceEvent",
  "refresh",
  "exhaust",
  "destroy",
  "returnToHand",
  "returnToTopDeck",
  "destroyAllMatching",
  "refreshAllMatching",
  "exhaustAllMatching",
  "returnAllMatchingToHand",
  "topDeckToTrash",
  "revealTop",
  "conditional",
  "setBattleRestriction",
  "selectTarget",
  "selectTrashTarget",
  "selectMultipleTargets",
  "chooseOption",
  "chooseYesNo",
  "chooseCardsFromHand",
  "chooseCardsFromTrash",
  "chooseCardsFromDeck",
  "chooseOrder",
  "chooseCoreDistribution",
  "setTurnProtection",
  "discardOpponentSetBurst",
  "performSpecifiedAttack",
  "trimCoresOnMatching",
  "scheduleAttackStepEndAfterBattle",
  "specialSummonFromHand",
  "specialSummonFromTrash",
  "specialSummonSource",
  "deployFromTrash",
  "forceLevel",
  "requireAttackIfAble",
  "emitSourceEvent",
  "dispatchSourceEvent",
  "revealTopAndRoute",
  "revealTopAndSummonOrHand",
  "oncePerTurn",
  "returnMagicUsedThisBattle",
  "returnUltimateTriggerRevealedMatchingToHand",
  "swapExhaustionState",
  "endCurrentStep",
  "upToNTimesPerTurn",
  "specialSummonBraveCombinedFromHand",
  "specialSummonEventSourceFromTrash",
  "combineBraveFromField",
  "returnEventSourceToHand",
  "suppressWhenSummonedForEndSteps"
]);

export function canonicalActionType(type) {
  const raw = String(type || "").trim();
  const compact = raw.replace(/[\s_-]+/g, "").toLowerCase();
  return ACTION_ALIASES[compact] || raw;
}

export function supportsCoreActionType(type) {
  return SUPPORTED_ACTION_TYPES.has(canonicalActionType(type));
}

export function listSupportedCoreActionTypes() {
  return [...SUPPORTED_ACTION_TYPES].sort();
}
