import { fieldCards, getDatabaseCard } from "../selectors.js";
import { otherPlayerId } from "../utils.js";
import { resolveCardEvent } from "./effectEngine.js";
import {
  entryMatchesTriggerContext,
  getEntryTriggerScope,
  getTriggeredEntries
} from "./normalizer.js";
import { EffectTriggerScope } from "./effectSchema.js";
import { normalizeCanonicalEvent } from "./canonicalEvents.js";

function eventInput(input = {}) {
  const eventPlayerId = input.eventPlayerId || input.sourcePlayerId || input.context?.eventPlayerId || null;
  return {
    ...input,
    event: normalizeCanonicalEvent(input.event || input.context?.event),
    context: {
      ...(input.context || {}),
      eventPlayerId,
      eventSourcePlayerId: input.sourcePlayerId || input.context?.eventSourcePlayerId || null,
      eventSourceInstanceId: input.sourceInstanceId || input.context?.eventSourceInstanceId || null,
      eventSourceCardId: input.sourceCardId || input.sourceCard?.id || input.context?.eventSourceCardId || null
    }
  };
}

function sourceDispatchInput(input) {
  return {
    ...input,
    dispatchMode: "source"
  };
}

function observerDispatchInput(input, playerId, physical) {
  return {
    event: input.event,
    sourcePlayerId: playerId,
    sourceInstanceId: physical.instanceId,
    sourcePhysical: physical,
    dispatchMode: "observerV2",
    context: {
      ...(input.context || {}),
      eventPlayerId: input.context?.eventPlayerId || null,
      eventSourcePlayerId: input.sourcePlayerId || input.context?.eventSourcePlayerId || null,
      eventSourceInstanceId: input.sourceInstanceId || input.context?.eventSourceInstanceId || null,
      eventSourceCardId: input.sourceCardId || input.sourceCard?.id || input.context?.eventSourceCardId || null
    }
  };
}

function appendQueuedEvents(match, events) {
  if (!match.pendingEffectDecision || !events.length) return match;
  return {
    ...match,
    pendingEffectDecision: {
      ...match.pendingEffectDecision,
      continuationEvents: [
        ...(match.pendingEffectDecision.continuationEvents || []),
        ...events
      ]
    }
  };
}

function observerCandidates(match, input, cardIndex) {
  const out = [];
  const event = input.event;
  for (const [playerId, player] of Object.entries(match.players || {})) {
    for (const physical of fieldCards(player)) {
      const card = getDatabaseCard(cardIndex, physical);
      if (!card) continue;
      const context = {
        ...(input.context || {}),
        sourcePlayerId: playerId,
        sourceInstanceId: physical.instanceId,
        sourcePhysical: physical,
        sourceCard: card,
        eventPlayerId: input.context?.eventPlayerId || null
      };
      const entries = getTriggeredEntries(card, event, { dispatchMode: "observerV2" })
        .filter(({ entry }) => getEntryTriggerScope(entry) === EffectTriggerScope.CONTROLLER_FIELD)
        .filter(({ entry }) => entryMatchesTriggerContext(entry, context, match));
      if (!entries.length) continue;

      // Source-scoped effects are handled by the first dispatch. Observer-scoped
      // effects may legally live on the same physical card, so they are not
      // excluded here.
      out.push(observerDispatchInput(input, playerId, physical));
    }
  }
  return out;
}

function mergeResult(base, current) {
  return {
    match: current.match,
    triggered: Number(base.triggered || 0) + Number(current.triggered || 0),
    automatic: Number(base.automatic || 0) + Number(current.automatic || 0),
    manualResolutionNeeded: Boolean(base.manualResolutionNeeded || current.manualResolutionNeeded),
    pendingEffectDecision: current.match?.pendingEffectDecision || current.pendingEffectDecision || null,
    notes: [...(base.notes || []), ...(current.notes || [])],
    dispatchedSources: Number(base.dispatchedSources || 0) + 1
  };
}

/**
 * Central trigger entry point for gameplay events.
 *
 * Legacy entries keep source-only behavior. Effect Schema v2 entries may opt
 * into controllerField observation, allowing a card already on the battlefield
 * to react to an event generated by another card/player.
 */
export function dispatchEffectEvent(match, rawInput = {}, cardIndex) {
  const input = eventInput(rawInput);
  if (!input.event) {
    return { match, triggered: 0, automatic: 0, manualResolutionNeeded: false, pendingEffectDecision: null, notes: [], dispatchedSources: 0 };
  }

  const dispatches = [];
  if (input.sourceInstanceId || input.sourcePhysical || input.sourceCardId || input.sourceCard) {
    dispatches.push(sourceDispatchInput(input));
  }
  dispatches.push(...observerCandidates(match, input, cardIndex));

  if (!dispatches.length) {
    return { match, triggered: 0, automatic: 0, manualResolutionNeeded: false, pendingEffectDecision: null, notes: [], dispatchedSources: 0 };
  }

  if (match.pendingEffectDecision) {
    const queued = appendQueuedEvents(match, dispatches);
    return {
      match: queued,
      triggered: 0,
      automatic: 0,
      manualResolutionNeeded: true,
      pendingEffectDecision: queued.pendingEffectDecision,
      notes: ["Trigger dispatch queued until the current effect decision is resolved."],
      dispatchedSources: 0
    };
  }

  let result = {
    match,
    triggered: 0,
    automatic: 0,
    manualResolutionNeeded: false,
    pendingEffectDecision: null,
    notes: [],
    dispatchedSources: 0
  };

  for (let index = 0; index < dispatches.length; index += 1) {
    const current = resolveCardEvent(result.match, dispatches[index], cardIndex);
    result = mergeResult(result, current);
    if (result.match.pendingEffectDecision) {
      result.match = appendQueuedEvents(result.match, dispatches.slice(index + 1));
      result.pendingEffectDecision = result.match.pendingEffectDecision;
      result.manualResolutionNeeded = true;
      break;
    }
  }

  return result;
}

export function getEventOpponentId(match, eventPlayerId) {
  return eventPlayerId ? otherPlayerId(match, eventPlayerId) : null;
}
